kind: "Pod"
metadata:
  labels:
    app: {{ .Values.objectStore.minio.serviceName }}
  name: {{ .Values.objectStore.minio.serviceName }}
spec:
  containers:
    - name: {{ .Values.objectStore.minio.serviceName }}
      image: "minio/minio:RELEASE.2025-05-24T17-08-30Z"
      command:
        - "/bin/bash"
        - "-c"
      args:
        - "minio server /data --console-address :{{ .Values.objectStore.minio.consolePort }} --address :{{ .Values.objectStore.minio.apiPort }}"
      volumeMounts:
        - mountPath: "/data"
          name: "data-volume"
  volumes:
    - name: "data-volume"
      emptyDir: { }
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ .Values.objectStore.minio.serviceName }}
  labels:
    app: {{ .Values.objectStore.minio.serviceName }}
spec:
  type: ClusterIP
  ports:
    - name: "api"
      port: {{ .Values.objectStore.minio.apiPort }}
      targetPort: {{ .Values.objectStore.minio.apiPort }}
    - name: "console"
      port: {{ .Values.objectStore.minio.consolePort }}
      targetPort: {{ .Values.objectStore.minio.consolePort }}
  selector:
    app: {{ .Values.objectStore.minio.serviceName }}