name: prestocpp-worker-with-clp-connector-runtime-image-build

on:
  # TODO: specifiy the branch to the release-0.293 when finalize the PR
  pull_request:
  push:

jobs:
  prestocpp-worker-with-clp-connector-runtime-image:
    name: prestocpp-worker-with-clp-connector-runtime-image
    runs-on: ubuntu-22.04
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          submodules: "recursive"

      - name: "Login to Image Registry"
        uses: "docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772"
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Update Metadata for Dependency Image"
        id: "meta-dependency"
        uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"
        with:
          images: >-
            ghcr.io/${{github.repository}}/prestissimo-with-clp-connector-dependency
          tags: |
            type=raw,value=ubuntu-22.04

      - name: "Build and push"
        uses: "docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4"
        with:
          context: "./presto-native-execution/"
          file: "./presto-native-execution/scripts/dockerfiles/ubuntu-22.04-dependency.dockerfile"
          push: >-
            ${{github.event_name != 'pull_request'
            && github.ref == 'refs/heads/release-0.293-clp-connector'}}
          tags: "${{steps.meta-dependency.outputs.tags}}"
          labels: "${{steps.meta-dependency.outputs.labels}}"

      - name: "Update Metadata for Runtime Image"
        id: "meta-runtime"
        uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"
        with:
          images: >-
            ghcr.io/${{github.repository}}/prestissimo-with-clp-connector-runtime
          tags: |
            type=raw,value=ubuntu-22.04

      - name: "Build and push"
        uses: "docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4"
        with:
          build-args: |-
            NUM_THREADS=4
            DEPENDENCY_IMAGE=${{ steps.meta-dependency.outputs.tags }}
            BASE_IMAGE=ubuntu:22.04
            OSNAME=ubuntu
            EXTRA_CMAKE_FLAGS=-DPRESTO_ENABLE_TESTING=OFF -DPRESTO_ENABLE_PARQUET=ON -DPRESTO_ENABLE_S3=ON
          context: "./presto-native-execution/"
          file: "./presto-native-execution/scripts/dockerfiles/prestissimo-runtime.dockerfile"
          push: >-
            ${{github.event_name != 'pull_request'
            && github.ref == 'refs/heads/release-0.293-clp-connector'}}
          tags: "${{steps.meta-runtime.outputs.tags}}"
          labels: "${{steps.meta-runtime.outputs.labels}}"
