name: prestocpp-worker-with-clp-connector-runtime-image-build

on:
  # TODO: specifiy the branch to the release-0.293 when finalize the PR
  pull_request:
  push:

jobs:
  prestocpp-worker-with-clp-connector-runtime-image:
    name: prestocpp-worker-with-clp-connector-runtime-image
    runs-on: ubuntu-22.04
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          submodules: "recursive"

      - name: "Login to image registry"
        uses: "docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772"
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Set up metadata for dependency image"
        id: "meta-dependency"
        uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"
        with:
          images: >-
            ghcr.io/${{github.repository}}/prestissimo-worker-dev-env
          tags: |-
            type=raw,value=dev

      - name: "Set up metadata for runtime image"
        id: "meta-runtime"
        uses: "docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804"
        with:
          images: >-
            ghcr.io/${{github.repository}}/prestissimo-worker
          tags: |-
            type=raw,value=dev

      - name: Check for dependency changes or missing dependency image
        id: dependency-changes
        run: |
          git fetch origin ${{ github.event.before }} --depth=1 || true
          dep_changed=false
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^presto-native-execution/scripts'; then
            dep_changed=true
          fi

          velox_old_sha=$(git ls-tree ${{ github.event.before }} presto-native-execution/velox | awk '{print $3}')
          velox_new_sha=$(git ls-tree ${{ github.sha }} presto-native-execution/velox | awk '{print $3}')
          cd presto-native-execution/velox
          if git diff --name-only ${velox_old_sha} ${velox_new_sha} | grep -q '^scripts'; then
            dep_changed=true
          fi
          echo "dep-changed=${dep_changed}" >> $GITHUB_OUTPUT

          image_exists=true
          if ! docker manifest inspect "${{ steps.meta-dependency.outputs.tags }}" > /dev/null 2>&1; then
            image_exists=false
          fi
          echo "image-exists=${image_exists}" >> $GITHUB_OUTPUT

      - name: "Build and push dependency image"
        if: steps.dependency-changes.outputs.dep-changed == 'true' || steps.dependency-changes.outputs.image-exists == 'false'
        uses: "docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4"
        with:
          context: "./presto-native-execution/"
          file: "./presto-native-execution/scripts/dockerfiles/ubuntu-22.04-dependency.dockerfile"
          push: >-
            ${{github.event_name != 'pull_request'
            && github.ref == 'refs/heads/release-0.293-clp-connector'}}
          tags: "${{steps.meta-dependency.outputs.tags}}"
          labels: "${{steps.meta-dependency.outputs.labels}}"

      - name: Get number of cores
        id: get-cores
        run: |-
          echo "num-threads=$(nproc)" >> $GITHUB_OUTPUT

      - name: "Build and push runtime image"
        uses: "docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4"
        with:
          build-args: |-
            NUM_THREADS=${{steps.get-cores.outputs.num-threads}}
            DEPENDENCY_IMAGE=${{steps.meta-dependency.outputs.tags}}
            BASE_IMAGE=ubuntu:22.04
            OSNAME=ubuntu
            EXTRA_CMAKE_FLAGS=-DPRESTO_ENABLE_TESTING=OFF -DPRESTO_ENABLE_PARQUET=ON -DPRESTO_ENABLE_S3=ON
          context: "./presto-native-execution/"
          file: "./presto-native-execution/scripts/dockerfiles/prestissimo-runtime.dockerfile"
          push: >-
            ${{github.event_name != 'pull_request'
            && github.ref == 'refs/heads/release-0.293-clp-connector'}}
          tags: "${{steps.meta-runtime.outputs.tags}}"
          labels: "${{steps.meta-runtime.outputs.labels}}"
