name: "presto-coordinator-runtime-image-build"

on:
  pull_request:
    paths:
      - ".github/workflows/presto-coordinator-runtime-image-build.yaml"
      - "docker/**/*"
  push:
    paths:
      - ".github/workflows/presto-coordinator-runtime-image-build.yaml"
      - "docker/**/*"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency. Exclude the `release-0.293-clp-connector` branch so
  # that each commit to release-0.293-clp-connector is checked completely.
  cancel-in-progress: "${{github.ref != 'refs/heads/release-0.293-clp-connector'}}"

jobs:
  presto-coordinator-runtime-image:
    name: presto-coordinator-runtime-image
    runs-on: ubuntu-22.04
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          submodules: "recursive"

      - name: "Workaround actions/runner-images/issues/6775"
        shell: "bash"
        run: "chown $(id -u):$(id -g) -R ."

      - uses: "./.github/actions/yscope-image-build"
        with:
          dockerfile_path: "./docker/Dockerfile"
          image_name_prefix: "yscope-presto-with-clp-connector-coordinator"
          image_registry: "ghcr.io"
          image_registry_username: "${{github.actor}}"
          image_registry_password: "${{secrets.GITHUB_TOKEN}}"
          platform_id: "centos"
          platform_version_id: "stream9"
