name: web ui checks

on:
  pull_request:
    branches: [release-0.293-clp-connector]
  push:
    branches: [release-0.293-clp-connector]

env:
  # An envar that signals to tests we are executing in the CI environment
  CONTINUOUS_INTEGRATION: true
  RETRY: .github/bin/retry

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"

  # Cancel in-progress jobs for efficiency. Exclude the `release-0.293-clp-connector` branch so
  # that each commit to release-0.293-clp-connector is checked completely.
  cancel-in-progress: "${{github.ref != 'refs/heads/release-0.293-clp-connector'}}"

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      codechange: ${{ steps.filter.outputs.codechange }}
    steps:
    - uses: "actions/checkout@v4"
      with:
        submodules: "recursive"
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          codechange:
            - '!presto-docs/**'
            - 'presto-ui/**'
  web-ui-checks:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.codechange == 'true'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Web UI Checks
        run: presto-ui/bin/check_webui.sh
